name: MCRS
version: ${project.version}
main: com.waldxn.MCRS.MCRS
api-version: '1.21'
commands:
  stats:
    description: Lists player stats
    usage: /stats [player]
    permission: mcrs.player.stats
  saveall:
    description: Saves all player stats
    usage: /saveall
    permission: mcrs.admin.saveall
  setstat:
    description: Sets a player's stat
    usage: /setstat <player> <stat> <value>
    permission: mcrs.admin.setstat